/**
 * This script helps troubleshoot environment variable issues in Next.js
 * Run this with: node reload-env.js
 */

const fs = require('fs');
const path = require('path');

// Function to create or update .env.local
function updateEnvLocal() {
  console.log('Checking environment files...');
  
  // Read from .env
  try {
    const envPath = path.join(process.cwd(), '.env');
    if (fs.existsSync(envPath)) {
      const envContent = fs.readFileSync(envPath, 'utf8');
      
      // Extract ABLY_API_KEY
      const ablyKeyMatch = envContent.match(/ABLY_API_KEY=([^\r\n]+)/);
      const ablyApiKey = ablyKeyMatch ? ablyKeyMatch[1].trim() : null;
      
      if (ablyApiKey) {
        console.log('Found ABLY_API_KEY in .env file:', ablyApiKey.slice(0, 5) + '...');
        
        // Create/update .env.local
        const envLocalPath = path.join(process.cwd(), '.env.local');
        const envLocalContent = `# Generated by reload-env.js\nABLY_API_KEY=${ablyApiKey}\n`;
        
        fs.writeFileSync(envLocalPath, envLocalContent, 'utf8');
        console.log('Created/updated .env.local with ABLY_API_KEY');
        
        return true;
      } else {
        console.log('Could not find ABLY_API_KEY in .env file');
      }
    } else {
      console.log('.env file not found');
    }
  } catch (err) {
    console.error('Error processing environment files:', err);
  }
  
  return false;
}

// Run the function
const result = updateEnvLocal();

console.log('\nNext steps:');
if (result) {
  console.log('1. Restart your Next.js server');
  console.log('2. Try the anonymous chat functionality again');
} else {
  console.log('1. Make sure your ABLY_API_KEY is properly set in .env file');
  console.log('2. Run this script again');
} 